# Generated by Django 3.2.6 on 2021-09-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('exfm_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Exfm Name')),
                ('web_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hiển thị')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tỉnh/thành')),
                ('head_of_endo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trưởng Khoa')),
                ('phone_head', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email_head', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('nurse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Điều dưỡng trưởng')),
                ('phone_nurse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email_nurse', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('vie_name', models.CharField(max_length=100, verbose_name='Tên tiếng Việt')),
                ('address', models.TextField(blank=True, max_length=150, null=True, verbose_name='Địa chỉ')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Khu vực')),
                ('contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Người đại diện')),
                ('contact_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('engineer1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kỹ sư')),
                ('engineer_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại')),
                ('engineer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Exfm',
            fields=[
                ('rma', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='rma')),
                ('location', models.CharField(blank=True, max_length=10, null=True, verbose_name='Location')),
                ('model_d', models.CharField(blank=True, max_length=20, null=True, verbose_name='Model')),
                ('sn', models.CharField(blank=True, max_length=15, null=True, verbose_name='SN')),
                ('install_date', models.DateTimeField(blank=True, null=True, verbose_name='installed date')),
                ('warranty_date', models.DateTimeField(blank=True, null=True, verbose_name='Warranty_Date')),
                ('receive_date', models.DateTimeField(blank=True, null=True, verbose_name='Receive')),
                ('inspection_date', models.DateTimeField(blank=True, null=True, verbose_name='Inspection')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('wr_report', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warranty')),
                ('repair_size', models.CharField(blank=True, max_length=5, null=True, verbose_name='MJ_mn')),
                ('issue_part', models.CharField(blank=True, max_length=50, null=True, verbose_name='Issue')),
                ('pic', models.CharField(blank=True, max_length=30, null=True, verbose_name='PIC')),
                ('repair_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status')),
                ('e_score', models.CharField(blank=True, max_length=2, null=True, verbose_name='e_score')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_s', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('tr_date', models.DateField(blank=True, null=True, verbose_name='Technical_Report')),
                ('part_list_date', models.DateField(blank=True, null=True, verbose_name='Part_List')),
                ('quotation_date', models.DateField(blank=True, null=True, verbose_name='Quotation')),
                ('repair_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('p_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('p_score', models.CharField(blank=True, max_length=2, null=True, verbose_name='Score')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dealer')),
                ('rma_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.exfm')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dealer'),
        ),
    ]
