# Generated by Django 3.2.6 on 2021-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfm',
            name='e_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='e_score'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='p_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
