# Generated by Django 3.2.6 on 2021-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfm',
            name='w_score',
            field=models.FloatField(blank=True, null=True, verbose_name='w_score'),
        ),
    ]
