# Generated by Django 3.2.6 on 2021-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='p_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
