# Generated by Django 3.2.6 on 2021-09-25 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pending_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_code', models.CharField(max_length=15, verbose_name='R-Code.')),
                ('r_description', models.CharField(max_length=50, verbose_name='Description')),
                ('vie_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên Tiếng Việt')),
                ('rma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exfm')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=15, verbose_name='Part No.')),
                ('part_description', models.CharField(max_length=50, verbose_name='Part Name')),
                ('vie_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên Tiếng Việt')),
                ('rma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exfm')),
            ],
        ),
    ]
