# Generated by Django 3.2.6 on 2021-09-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_part_rcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Số máy')),
                ('model', models.CharField(max_length=20, verbose_name='Kiểu máy')),
                ('type_s', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại máy')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='Bảo hành đến')),
                ('last_repair_date', models.DateField(blank=True, null=True, verbose_name='Lần cuối sửa chữa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
