# Generated by Django 3.2.6 on 2021-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='exfm',
            name='w_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='w_score'),
        ),
        migrations.AddField(
            model_name='pending',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
    ]
