# Generated by Django 3.2.6 on 2021-10-27 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_pending_rma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='rma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exfm'),
        ),
    ]
