# Generated by Django 3.2.6 on 2021-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Xác Nhận'),
        ),
    ]
