# Generated by Django 3.2.6 on 2021-12-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_tri_1', models.CharField(max_length=100, verbose_name='Bảo trì 1')),
                ('bao_tri_2', models.CharField(max_length=100, verbose_name='Bảo trì 2')),
                ('bao_tri_3', models.CharField(max_length=100, verbose_name='Bảo trì 3')),
                ('bao_tri_4', models.CharField(max_length=100, verbose_name='Bảo trì 4')),
                ('bao_tri_5', models.CharField(max_length=100, verbose_name='Bảo trì 5')),
            ],
        ),
    ]
