# Generated by Django 3.2.6 on 2021-09-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_auto_20210922_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_e',
            field=models.IntegerField(choices=[(1, 'Bảo trì'), (2, 'Training')], default=1, verbose_name='Type'),
        ),
    ]
