# Generated by Django 3.2.6 on 2021-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_alter_comment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='verify_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận'),
        ),
    ]
