# Generated by Django 3.2.6 on 2021-10-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_event_type_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
