# Generated by Django 3.2.6 on 2021-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_comment_verify_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='verifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người xác nhận'),
        ),
    ]
